image:
  bff:
    repository: dmportella/expressjs
    tag: latest
    pullPolicy: Always
  sidecar:
    repository: ghcr.io/joebui/argocd-deployment
    tag: main
    pullPolicy: Always

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
