image:
  bff:
    repository: dmportella/expressjs
    tag: latest
    pullPolicy: Always
  sidecar:
    repository: ghcr.io/joebui/argocd-deployment
    tag: main
    pullPolicy: Always

autoscaling:
  enabled: true

ingress:
  enabled: true
  annotations: []
  hosts:
    - host: "*.elb.ap-southeast-1.amazonaws.com"
      paths:
        - path: /stg
          pathType: Prefix
