replicaCount: 1

image:
  bff:
    repository: dmportella/expressjs
    tag: latest
    pullPolicy: Always
  sidecar:
    repository: ghcr.io/joebui/argocd-deployment
    tag: main
    pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  target_port: 80
  annotations:
    # traefik.ingress.kubernetes.io/service.nativelb: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie: "false"

ingress:
  enabled: true
  annotations: []
  hosts:
    - host: "hello-world.com"
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 256m
    memory: 256Mi
  requests:
    cpu: 128m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
