static_resources:
  clusters:
    - name: backend_service
      type: strict_dns
      hosts:
        - localhost:8080

http_filters:
  - name: router

admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      port_value: 9901

listeners:
  - name: http_listener
    address:
      socket_address:
        port_value: 80
    filter_chains:
      - filters:
          - name: router
            config:
              cluster: backend_service
