replicaCount: 1

image:
  repository: dmportella/expressjs
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  target_port: 8080
  annotations:
    traefik.ingress.kubernetes.io/service.nativelb: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie: "false"
    traefik.ingress.kubernetes.io/service.passhostheader: "false"

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "false"
  hosts:
    - host: "*.elb.ap-southeast-1.amazonaws.com"
      paths:
        - path: /
          pathType: Exact
  tls: []

resources:
  limits:
    cpu: 256m
    memory: 256Mi
  requests:
    cpu: 128m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
